In [2]:
import csv
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [3]:
df = pd.DataFrame([ row for row in csv.DictReader(open('Resources/Global Ecological Footprint 2023.csv',errors='ignore')) ])
df.head()

,Country,Region,SDGi,Life Exectancy,HDI,Per Capita GDP,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,...,Built up land,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required
0,Afghanistan,Middle East/Central Asia,52.5,62,0.48,,LI,40.8,0.4,0.1,...,0.028232273,0.8,0.3,0.1,0.012981282,0.000565167,0.513827024,-0.287637599,0.530695582,1.559794611
1,Albania,Other Europe,71.6,76,0.8,"$14,889",UM,2.9,0.8,0.2,...,0.073005587,2.1,0.6,0.2,0.223326157,0.081391904,1.176752316,-0.894486045,1.37148542,1.760131111
2,Algeria,Africa,71.5,76,0.75,"$11,137",UM,45.4,0.7,0.2,...,0.037775208,2.2,0.4,0.2,0.023911707,0.007179154,0.663374969,-1.559593496,1.471954604,3.350998407
3,Angola,Africa,50.9,62,0.59,"$6,304",LM,35,0.2,0.1,...,0.061359798,0.9,0.2,0.8,0.416887822,0.153498781,1.588191242,0.730345635,0.568028656,0.540139993
4,Antigua and Barbuda,Central America/Caribbean,,78,0.79,"$18,749",HI,0.1,,,...,,2.9,,,,,0.917277482,-2.01945766,1.944580357,3.201577712

In [4]:
df.to_csv('Resources/clean_data.csv')

In [5]:
df = pd.read_csv('Resources/clean_data.csv', index_col='Unnamed: 0')
df[:5]

,Country,Region,SDGi,Life Exectancy,HDI,Per Capita GDP,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,...,Built up land,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required
0,Afghanistan,Middle East/Central Asia,52.5,62,0.48,NaN,LI,40.8,0.4,0.1,...,0.028232,0.8,0.3,0.1,0.012981,0.000565,0.513827,-0.287638,0.530696,1.559795
1,Albania,Other Europe,71.6,76,0.8,"$14,889",UM,2.9,0.8,0.2,...,0.073006,2.1,0.6,0.2,0.223326,0.081392,1.176752,-0.894486,1.371485,1.760131
2,Algeria,Africa,71.5,76,0.75,"$11,137",UM,45.4,0.7,0.2,...,0.037775,2.2,0.4,0.2,0.023912,0.007179,0.663375,-1.559593,1.471955,3.350998
3,Angola,Africa,50.9,62,0.59,"$6,304",LM,35,0.2,0.1,...,0.061360,0.9,0.2,0.8,0.416888,0.153499,1.588191,0.730346,0.568029,0.540140
4,Antigua and Barbuda,Central America/Caribbean,NaN,78,0.79,"$18,749",HI,0.1,NaN,NaN,...,NaN,2.9,NaN,NaN,NaN,NaN,0.917277,-2.019458,1.944580,3.201578

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 182 entries, 0 to 181
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Country                                   182 non-null    object
 1   Region                                    182 non-null    object
 2   SDGi                                      159 non-null    object
 3   Life Exectancy                            176 non-null    object
 4   HDI                                       173 non-null    object
 5   Per Capita GDP                            165 non-null    object
 6   Income Group                              178 non-null    object
 7   Population (millions)                     182 non-null    object
 8   Cropland Footprint                        152 non-null    float64
 9   Grazing Footprint                         152 non-null    float64
 10  Forest Product Footprint                  152 non-null    float64
 11  Carbon Footprint                          152 non-null    float64
 12  Fish Footprint                            152 non-null    float64
 13  Built up land                             152 non-null    float64
 14  Total Ecological Footprint (Consumption)  181 non-null    float64
 15  Cropland                                  152 non-null    float64
 16  Grazing land                              152 non-null    float64
 17  Forest land                               152 non-null    float64
 18  Fishing ground                            152 non-null    float64
 19  Total biocapacity                         181 non-null    float64
 20  Ecological (Deficit) or Reserve           181 non-null    float64
 21  Number of Earths required                 181 non-null    float64
 22  Number of Countries required              181 non-null    float64
dtypes: float64(15), object(8)
memory usage: 34.1+ KB

In [7]:
df = df.dropna()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 134 entries, 1 to 179
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Country                                   134 non-null    object
 1   Region                                    134 non-null    object
 2   SDGi                                      134 non-null    object
 3   Life Exectancy                            134 non-null    object
 4   HDI                                       134 non-null    object
 5   Per Capita GDP                            134 non-null    object
 6   Income Group                              134 non-null    object
 7   Population (millions)                     134 non-null    object
 8   Cropland Footprint                        134 non-null    float64
 9   Grazing Footprint                         134 non-null    float64
 10  Forest Product Footprint                  134 non-null    float64
 11  Carbon Footprint                          134 non-null    float64
 12  Fish Footprint                            134 non-null    float64
 13  Built up land                             134 non-null    float64
 14  Total Ecological Footprint (Consumption)  134 non-null    float64
 15  Cropland                                  134 non-null    float64
 16  Grazing land                              134 non-null    float64
 17  Forest land                               134 non-null    float64
 18  Fishing ground                            134 non-null    float64
 19  Total biocapacity                         134 non-null    float64
 20  Ecological (Deficit) or Reserve           134 non-null    float64
 21  Number of Earths required                 134 non-null    float64
 22  Number of Countries required              134 non-null    float64
dtypes: float64(15), object(8)
memory usage: 25.1+ KB

In [9]:
# removing ($ and comma) from Per Capita GDP column
df['Per Capita GDP'] = df['Per Capita GDP'].str.replace('$','').str.replace(',','')

# reviewed column for values that could not turn into float and collected row indexes
nan = [40,42]

# removed rows with issues
df = df.drop(nan)

# changed column type from object to float
df["Per Capita GDP"] = df["Per Capita GDP"].astype('float')

df[:5]

,Country,Region,SDGi,Life Exectancy,HDI,Per Capita GDP,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,...,Built up land,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required
1,Albania,Other Europe,71.6,76,0.8,14889.0,UM,2.9,0.8,0.2,...,0.073006,2.1,0.6,0.2,0.223326,0.081392,1.176752,-0.894486,1.371485,1.760131
2,Algeria,Africa,71.5,76,0.75,11137.0,UM,45.4,0.7,0.2,...,0.037775,2.2,0.4,0.2,0.023912,0.007179,0.663375,-1.559593,1.471955,3.350998
3,Angola,Africa,50.9,62,0.59,6304.0,LM,35,0.2,0.1,...,0.061360,0.9,0.2,0.8,0.416888,0.153499,1.588191,0.730346,0.568029,0.540140
5,Argentina,South America,72.8,75,0.84,22117.0,UM,46,0.9,0.5,...,0.083517,3.2,1.8,1.2,0.591673,1.527615,5.231663,2.011045,2.132556,0.615601
6,Armenia,Middle East/Central Asia,71.1,72,0.76,13548.0,LM,3,0.7,0.2,...,0.052182,2.3,0.4,0.3,0.098200,0.016853,0.846625,-1.479770,1.540439,2.747847

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 132 entries, 1 to 179
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Country                                   132 non-null    object
 1   Region                                    132 non-null    object
 2   SDGi                                      132 non-null    object
 3   Life Exectancy                            132 non-null    object
 4   HDI                                       132 non-null    object
 5   Per Capita GDP                            132 non-null    float64
 6   Income Group                              132 non-null    object
 7   Population (millions)                     132 non-null    object
 8   Cropland Footprint                        132 non-null    float64
 9   Grazing Footprint                         132 non-null    float64
 10  Forest Product Footprint                  132 non-null    float64
 11  Carbon Footprint                          132 non-null    float64
 12  Fish Footprint                            132 non-null    float64
 13  Built up land                             132 non-null    float64
 14  Total Ecological Footprint (Consumption)  132 non-null    float64
 15  Cropland                                  132 non-null    float64
 16  Grazing land                              132 non-null    float64
 17  Forest land                               132 non-null    float64
 18  Fishing ground                            132 non-null    float64
 19  Total biocapacity                         132 non-null    float64
 20  Ecological (Deficit) or Reserve           132 non-null    float64
 21  Number of Earths required                 132 non-null    float64
 22  Number of Countries required              132 non-null    float64
dtypes: float64(16), object(7)
memory usage: 24.8+ KB

In [22]:
df.eq(' ').any()

Country                                     False
Region                                      False
SDGi                                        False
Life Exectancy                              False
HDI                                          True
Per Capita GDP                              False
Income Group                                False
Population (millions)                       False
Cropland Footprint                          False
Grazing Footprint                           False
Forest Product Footprint                    False
Carbon Footprint                            False
Fish Footprint                              False
Built up land                               False
Total Ecological Footprint (Consumption)    False
Cropland                                    False
Grazing land                                False
Forest land                                 False
Fishing ground                              False
Total biocapacity                           False
Ecological (Deficit) or Reserve             False
Number of Earths required                   False
Number of Countries required                False
dtype: bool

In [25]:
df[df.HDI==' ']

,Country,Region,SDGi,Life Exectancy,HDI,Per Capita GDP,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,...,Built up land,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required
150,Somalia,Africa,45.6,55,,1132.0,LI,16.8,0.2,0.3,...,0.017672,0.9,0.1,0.3,0.116078,0.196021,0.712411,-0.178978,0.59024,1.251229

In [26]:
df.drop(150, inplace=True)

In [30]:
df.eq( '1,480.60').any()

Country                                     False
Region                                      False
SDGi                                        False
Life Exectancy                              False
HDI                                         False
Per Capita GDP                              False
Income Group                                False
Population (millions)                        True
Cropland Footprint                          False
Grazing Footprint                           False
Forest Product Footprint                    False
Carbon Footprint                            False
Fish Footprint                              False
Built up land                               False
Total Ecological Footprint (Consumption)    False
Cropland                                    False
Grazing land                                False
Forest land                                 False
Fishing ground                              False
Total biocapacity                           False
Ecological (Deficit) or Reserve             False
Number of Earths required                   False
Number of Countries required                False
dtype: bool

In [33]:
df['Population (millions)'] = df['Population (millions)'].str.replace(',','')

In [35]:
df[['SDGi','HDI','Population (millions)']] = df[['SDGi','HDI','Population (millions)']].astype('float')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 131 entries, 1 to 179
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Country                                   131 non-null    object
 1   Region                                    131 non-null    object
 2   SDGi                                      131 non-null    float64
 3   Life Exectancy                            131 non-null    object
 4   HDI                                       131 non-null    float64
 5   Per Capita GDP                            131 non-null    float64
 6   Income Group                              131 non-null    object
 7   Population (millions)                     131 non-null    float64
 8   Cropland Footprint                        131 non-null    float64
 9   Grazing Footprint                         131 non-null    float64
 10  Forest Product Footprint                  131 non-null    float64
 11  Carbon Footprint                          131 non-null    float64
 12  Fish Footprint                            131 non-null    float64
 13  Built up land                             131 non-null    float64
 14  Total Ecological Footprint (Consumption)  131 non-null    float64
 15  Cropland                                  131 non-null    float64
 16  Grazing land                              131 non-null    float64
 17  Forest land                               131 non-null    float64
 18  Fishing ground                            131 non-null    float64
 19  Total biocapacity                         131 non-null    float64
 20  Ecological (Deficit) or Reserve           131 non-null    float64
 21  Number of Earths required                 131 non-null    float64
 22  Number of Countries required              131 non-null    float64
dtypes: float64(19), object(4)
memory usage: 24.6+ KB

In [38]:
df['Life Exectancy']=df['Life Exectancy'].astype('int')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 131 entries, 1 to 179
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Country                                   131 non-null    object
 1   Region                                    131 non-null    object
 2   SDGi                                      131 non-null    float64
 3   Life Exectancy                            131 non-null    int32
 4   HDI                                       131 non-null    float64
 5   Per Capita GDP                            131 non-null    float64
 6   Income Group                              131 non-null    object
 7   Population (millions)                     131 non-null    float64
 8   Cropland Footprint                        131 non-null    float64
 9   Grazing Footprint                         131 non-null    float64
 10  Forest Product Footprint                  131 non-null    float64
 11  Carbon Footprint                          131 non-null    float64
 12  Fish Footprint                            131 non-null    float64
 13  Built up land                             131 non-null    float64
 14  Total Ecological Footprint (Consumption)  131 non-null    float64
 15  Cropland                                  131 non-null    float64
 16  Grazing land                              131 non-null    float64
 17  Forest land                               131 non-null    float64
 18  Fishing ground                            131 non-null    float64
 19  Total biocapacity                         131 non-null    float64
 20  Ecological (Deficit) or Reserve           131 non-null    float64
 21  Number of Earths required                 131 non-null    float64
 22  Number of Countries required              131 non-null    float64
dtypes: float64(19), int32(1), object(3)
memory usage: 24.1+ KB

In [41]:
df

,Country,Region,SDGi,Life Exectancy,HDI,Per Capita GDP,Income Group,Population (millions),Cropland Footprint,Grazing Footprint,...,Built up land,Total Ecological Footprint (Consumption),Cropland,Grazing land,Forest land,Fishing ground,Total biocapacity,Ecological (Deficit) or Reserve,Number of Earths required,Number of Countries required
1,Albania,Other Europe,71.6,76,0.80,14889.0,UM,2.9,0.8,0.2,...,0.073006,2.1,0.6,0.2,0.223326,0.081392,1.176752,-0.894486,1.371485,1.760131
2,Algeria,Africa,71.5,76,0.75,11137.0,UM,45.4,0.7,0.2,...,0.037775,2.2,0.4,0.2,0.023912,0.007179,0.663375,-1.559593,1.471955,3.350998
3,Angola,Africa,50.9,62,0.59,6304.0,LM,35.0,0.2,0.1,...,0.061360,0.9,0.2,0.8,0.416888,0.153499,1.588191,0.730346,0.568029,0.540140
5,Argentina,South America,72.8,75,0.84,22117.0,UM,46.0,0.9,0.5,...,0.083517,3.2,1.8,1.2,0.591673,1.527615,5.231663,2.011045,2.132556,0.615601
6,Armenia,Middle East/Central Asia,71.1,72,0.76,13548.0,LM,3.0,0.7,0.2,...,0.052182,2.3,0.4,0.3,0.098200,0.016853,0.846625,-1.479770,1.540439,2.747847
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,United Arab Emirates,Middle East/Central Asia,68.8,79,0.91,67026.0,HI,10.1,0.8,0.6,...,0.000000,8.7,0.0,0.0,0.061908,0.450008,0.543236,-8.171591,5.770586,16.042429
172,United Kingdom,Other Europe,80.6,81,0.93,47366.0,HI,68.5,0.7,0.2,...,0.097712,3.6,0.4,0.1,0.150714,0.286078,1.020497,-2.544800,2.360787,3.493686
173,United States of America,North America,74.6,76,0.92,65118.0,HI,334.8,1.3,0.3,...,0.051252,7.5,1.7,0.2,1.433904,0.313289,3.720832,-3.739800,4.940111,2.005098
178,Viet Nam,Asia-Pacific,72.8,74,0.70,11032.0,LM,99.0,0.5,0.0,...,0.078597,2.4,0.4,0.0,0.155677,0.149952,0.795070,-1.637204,1.610548,3.059195
179,Yemen,Middle East/Central Asia,52.1,64,0.46,1780.0,LM,31.2,0.3,0.1,...,0.019530,0.6,0.1,0.1,0.030011,0.146865,0.347502,-0.265756,0.406073,1.764761

In [40]:
df.to_csv('Resources/clean_data.csv')